#!/bin/sh

CURDIR=$(cd $(dirname $0) && pwd)
CONFIDR="$CURDIR/conf"
PACKAGEID="com.modouwifi.kms"
MTHLOG="/data/log/kms.log"
# to tp
TO_TP_TITLE="kms"
TO_TP_CONF_DIR="/data/conf/launcher/conf.d"
TO_TP_ICON="$CURDIR/res/kms.png"
TO_TP_PRESSED_ICON="$CURDIR/res/kms.png"

usage()
{
	return 0;
}

install()
{
    # to tp
    if [ ! -d $TO_TP_CONF_DIR ]; then
        mkdir -p $TO_TP_CONF_DIR
    fi
    echo "{" > "$TO_TP_CONF_FILE"
    echo "\"name\" : \"$TO_TP_TITLE\"," >> "$TO_TP_CONF_FILE"
    echo "\"icon\" : \"$TO_TP_ICON\"," >> "$TO_TP_CONF_FILE"
    echo "\"iconPressed\" : \"$TO_TP_PRESSED_ICON\"," >> "$TO_TP_CONF_FILE"
    echo "\"exec\" : \"$CURDIR/bin/vlmcsd && messagebox KMS激活服务器 ServerIs:modouwifi.net 1 关闭程序 killallvlmcsd\"," >> "$TO_TP_CONF_FILE"
    echo "\"msgNum\" : 4" >> "$TO_TP_CONF_FILE"
    echo "}" >> "$TO_TP_CONF_FILE"
    /system/sbin/appInfo.sh set_status $PACKAGEID NOTRUNNING
    return 0;
}

uninstall()
{
    rm  $MTHLOG
    echo "uninstall";
    return 0;
}

stop()
{
    killall vlmcsd
    /system/sbin/appInfo.sh set_status $PACKAGEID NOTRUNNING
    return 0;
}

start()
{
    chmod +x $CURDIR/bin/vlmcsd
    $CURDIR/bin/vlmcsd &
    /system/sbin/appInfo.sh set_status $PACKAGEID ISRUNNING
    return 0;
}

status()
{
    return 0;
}

set_config()
{
    /system/sbin/appInfo.sh set_status $PACKAGEID ISRUNNING
    return 0;
}

# main
if [ $# -lt 1 ]; then
    usage init
    exit 1
fi


case "$1" in
    "stop")
        stop;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    "start")
        start;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    "status")
        status;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    "set_config")
        set_config;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    "install")
        install;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    "uninstall")
        uninstall;
        if [ "0" != "$?" ]; then
            exit 1;
        fi
        exit 0;
        ;;
    *)
        usage init;
        exit 1;
        ;;
esac
